services:
  web:
    build: .
    image: lawest98/djangoapp:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
